# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('codigo', models.IntegerField(default=0, verbose_name='Codigo de Barras')),
                ('ref', models.CharField(blank=True, max_length=100, verbose_name='Ref')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Produto Base',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='EstabelecimentoProduto',
            fields=[
                ('produtobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.ProdutoBase')),
                ('slug', models.SlugField(unique=True, verbose_name='Ident')),
                ('preco_normal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Normal')),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Promocional')),
                ('em_promocao', models.BooleanField(default=False, verbose_name='Em Promoção')),
                ('promocao_relampago', models.TimeField(null=True, verbose_name='Tempo em Promoção')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta Ativo')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos', verbose_name='Imagem')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('secao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Categoria')),
            ],
            options={
                'ordering': ('nome_produto',),
                'verbose_name': 'Estabelecimento Produto',
                'verbose_name_plural': 'Produtos do Estabelecimento',
            },
            bases=('produto.produtobase',),
        ),
    ]
