# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentoproduto',
            name='data_inicio_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
