# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_estabelecimentoproduto_data_inicio_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimentoproduto',
            name='promocao_relampago',
            field=models.IntegerField(null=True, verbose_name='Tempo em Promoção'),
        ),
    ]
