# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_remove_estabelecimentoproduto_data_inicio_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentoproduto',
            name='fim_da_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimentoproduto',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Desejo iniciar a promoção assim que salvar.'),
        ),
        migrations.AlterField(
            model_name='estabelecimentoproduto',
            name='promocao_relampago',
            field=models.IntegerField(null=True, verbose_name='Expira em'),
        ),
    ]
