# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:33
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(help_text='Um nome curto que será usado para acessar a plataforma.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+_-]+$', 32), 'Informe um nome de usuário válido. Este valor deve conter apenas letras, numerose os caracteres: @/./+/-/_. ', 'Inválido')])),
                ('nome_estabelecimento', models.CharField(max_length=100, unique=True, verbose_name='Nome do Estabelecimento')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='UF')),
                ('telefone_principal', models.CharField(max_length=15, verbose_name='Telefone Principal')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Estabelecimentos',
                'verbose_name': 'Estabelecimento',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
