# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='login',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='username',
            field=models.CharField(default='slug', help_text='Um nome curto que será usado para acessar a plataforma.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+_-]+$', 32), 'Informe um nome de usuário válido. Este valor deve conter apenas letras, numerose os caracteres: @/./+/-/_. ', 'Inválido')], verbose_name='Login'),
            preserve_default=False,
        ),
    ]
