# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0003_estabelecimento_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
    ]
