# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('texto_slogan', models.TextField(max_length=1000)),
                ('img', models.CharField(max_length=5000)),
                ('validade_inicio', models.DateTimeField()),
                ('validade_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('preco_promocional', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('img', models.CharField(max_length=5000)),
                ('ativo', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='utils.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='catalogo',
            name='produtos',
            field=models.ManyToManyField(to='utils.Produto'),
        ),
    ]
