# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20170427_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(),
        ),
    ]
